jrc_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: JRCUserBundle:Default:index }
    
jrc_user_index:
    path:       /user/index
    defaults: { _controller: JRCUserBundle:User:index }
    
jrc_user_add:
    path:       /user/add
    defaults: { _controller: JRCUserBundle:User:add }
    
jrc_user_create:
    path:       /user/create
    defaults: { _controller: JRCUserBundle:User:create }
    methods: POST
    
jrc_user_edit:
    path:       /user/edit/{id}
    defaults: { _controller: JRCUserBundle:User:edit }
    
jrc_user_update:
    path:       /user/update/{id}
    defaults: { _controller: JRCUserBundle:User:update }
    methods: [POST, PUT]
    
jrc_user_view:
    path:       /user/view/{id}
    defaults: { _controller: JRCUserBundle:User:view }
    
jrc_user_delete:
    path:       /user/delete{id}
    defaults: { _controller: JRCUserBundle:User:delete }
    methods: [POST, DELETE]
    
jrc_user_redirect_add:
    path:       /user/create
    defaults:
        _controller: JRCUserBundle:User:add
        path: /user/add
        permanent: true
        
jrc_user_redirect_edit:
    path:       /user/update/{id}
    defaults:
        _controller: JRCUserBundle:User:edit
        path: /user/edit{id}
        permanent: true
    